openapi: 3.0.0
info:
  title: eBook Digital Store API
  version: 1.0.0
  description: API for managing eBook digital store operations.

x-json-schema-faker:
  min-items: 2
  max-items: 10
  optionalsProbability: 1
  resolve-json-path: true

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  example: johndoe
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  example: password123
                confirmPassword:
                  type: string
                  example: password123
      responses:
        "200":
          description: User registered successfully
          content:
            application/json:
              example:
                message: Registration successful
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        "400":
          description: Bad request, invalid input data

  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
      responses:
        "200":
          description: User logged in successfully
          content:
            application/json:
              example:
                message: Login successful
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 (example JWT token)
        "401":
          description: Unauthorized, incorrect credentials
  /auth/products:
    get:
      summary: Get a list of eBooks
      responses:
        "200":
          description: List of eBooks retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
components:
  schemas:
    $ref: "./schemas/_index.yaml"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
