import { Suspense } from "react";

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import { UserProvider } from "@/contexts/userContext";

import "./globals.css";
import { NotificationProvider } from "./_contexts/notificationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NotificationProvider>
          <UserProvider>{children}</UserProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
