import "./globals.css";

import type { Metadata } from "next";

import { UserProvider } from "@/contexts/userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <Auth0Provider
          domain="dev-qa9pe6p5.us.auth0.com"
          clientId="pHXwG90qhKI3mRJNqyrddmJoHWaroUxA"
          authorizationParams={{
            redirect_uri:
              typeof window !== "undefined" ? window.location.origin : "",
          }}
        > */}
        <UserProvider>{children}</UserProvider>
        {/* </Auth0Provider> */}
      </body>
    </html>
  );
}
